cities:
  - 徐州
  - 宿州
  - 济宁
  - 泰安
  - 青岛
  - 滁州
  - 南京
  - 扬州
  - 镇江
  - 安庆
  - 黄山
  - 歙县
  - 池州
  - 无锡
  - 苏州
  - 上海
  - 杭州
  - 嘉兴
  - 湖州
  - 绍兴
  - 义乌
  - 金华
  - 东阳
  - 磐安
  - 仙居
  - 温州
  - 福鼎
  - 宁德
  - 福州
  - 莆田
  - 泉州
  - 厦门
  - 深圳
  - 广州
  - 武汉
  - 长沙
  - 张家界
  - 凤凰
  - 北京
  - 香港
  - 郑州
  - 洛阳
  - 西安市
  - 渭南
  - 杨凌
  - 宝鸡
  - 汉中
  - 安康
  - 延安
  - 榆林
  - 太原
  - 洪洞
  - 平遥
  - 灵石
  - 介休
  - 代县
  - 大同市
  - 天水
  - 兰州
  - 西宁
  - 青海湖
  - 张掖
  - 嘉峪关
  - 敦煌
  - 成都
  - 重庆
  - 武隆
  - 都江堰
  - 昆明
  - 大理
  - 丽江